[package]
name = "diary-cli"
description = "small command line diary utility."

readme = "README.md"
license = "MIT"

repository = "https://github.com/TheLazyFerret/diary-cli"

version = "0.0.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"